CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    owner_id BIGINT NOT NULL,

    name VARCHAR(150) NOT NULL,
    description TEXT,

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_projects_owner
        FOREIGN KEY (owner_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_projects_status
        CHECK (status IN ('PLANNED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED'))
);

CREATE INDEX idx_projects_owner_id
    ON projects (owner_id);

CREATE INDEX idx_projects_status
    ON projects (status);
