CREATE TABLE github_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    github_user_id BIGINT NOT NULL,
    github_login VARCHAR(100) NOT NULL,
    display_name VARCHAR(255),
    avatar_url VARCHAR(500),

    access_token TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_github_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_github_accounts_user
        UNIQUE (user_id),

    CONSTRAINT uk_github_accounts_github_user
        UNIQUE (github_user_id)
);

CREATE INDEX idx_github_accounts_github_login
    ON github_accounts (github_login);
