CREATE TABLE repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    github_account_id BIGINT NOT NULL,

    github_repository_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(500) NOT NULL,
    description TEXT,

    url VARCHAR(500) NOT NULL,
    default_branch VARCHAR(255),

    is_private BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,

    github_created_at TIMESTAMPTZ,
    github_updated_at TIMESTAMPTZ,

    synced_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_repositories_github_account
        FOREIGN KEY (github_account_id)
        REFERENCES github_accounts (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_repositories_github_repository
        UNIQUE (github_repository_id)
);

CREATE INDEX idx_repositories_github_account_id
    ON repositories (github_account_id);

CREATE INDEX idx_repositories_full_name
    ON repositories (full_name);
