CREATE TABLE project_repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    project_id BIGINT NOT NULL,
    repository_id BIGINT NOT NULL,

    role VARCHAR(30) NOT NULL DEFAULT 'SECONDARY',
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,

    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_project_repositories_project
        FOREIGN KEY (project_id)
        REFERENCES projects (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_project_repositories_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_project_repositories_pair
        UNIQUE (project_id, repository_id),

    CONSTRAINT ck_project_repositories_role
        CHECK (role IN ('PRIMARY', 'SECONDARY'))
);

CREATE INDEX idx_project_repositories_project_id
    ON project_repositories (project_id);

CREATE INDEX idx_project_repositories_repository_id
    ON project_repositories (repository_id);

CREATE INDEX idx_project_repositories_primary
    ON project_repositories (project_id, is_primary);
