CREATE TABLE commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT NOT NULL,

    github_sha VARCHAR(64) NOT NULL,
    author_name VARCHAR(255),
    author_email VARCHAR(255),

    message TEXT NOT NULL,

    branch_name VARCHAR(255),
    commit_url VARCHAR(500),

    committed_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_commits_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_commits_repository_sha
        UNIQUE (repository_id, github_sha)
);

CREATE INDEX idx_commits_repository_id
    ON commits (repository_id);

CREATE INDEX idx_commits_committed_at
    ON commits (committed_at);

CREATE INDEX idx_commits_repository_committed_at
    ON commits (repository_id, committed_at DESC);

CREATE INDEX idx_commits_branch_name
    ON commits (branch_name);
