CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL,

    is_default BOOLEAN NOT NULL DEFAULT FALSE,

    latest_commit_id BIGINT,

    last_updated_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_branches_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_branches_latest_commit
        FOREIGN KEY (latest_commit_id)
        REFERENCES commits (id)
        ON DELETE SET NULL,

    CONSTRAINT uk_branches_repository_name
        UNIQUE (repository_id, name)
);

CREATE INDEX idx_branches_repository_id
    ON branches (repository_id);

CREATE INDEX idx_branches_repository_default
    ON branches (repository_id, is_default);

CREATE INDEX idx_branches_last_updated_at
    ON branches (last_updated_at);
