CREATE TABLE pull_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT NOT NULL,

    github_pull_request_id BIGINT NOT NULL,

    title VARCHAR(500) NOT NULL,
    author_login VARCHAR(255),

    state VARCHAR(30) NOT NULL,

    created_at_github TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    merged_at TIMESTAMPTZ,

    url VARCHAR(500) NOT NULL,

    source_branch VARCHAR(255),
    target_branch VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pull_requests_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_pull_requests_repository_github_id
        UNIQUE (repository_id, github_pull_request_id),

    CONSTRAINT ck_pull_requests_state
        CHECK (state IN ('OPEN', 'CLOSED'))
);

CREATE INDEX idx_pull_requests_repository_id
    ON pull_requests (repository_id);

CREATE INDEX idx_pull_requests_state
    ON pull_requests (state);

CREATE INDEX idx_pull_requests_created_at_github
    ON pull_requests (created_at_github);

CREATE INDEX idx_pull_requests_repository_created_at
    ON pull_requests (repository_id, created_at_github DESC);
