CREATE TABLE webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT,

    github_delivery_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(100) NOT NULL,

    action VARCHAR(100),

    payload JSONB NOT NULL,

    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,

    processing_status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    processing_error TEXT,

    CONSTRAINT fk_webhook_events_repository
        FOREIGN KEY (repository_id)
        REFERENCES repositories (id)
        ON DELETE SET NULL,

    CONSTRAINT uk_webhook_events_delivery_id
        UNIQUE (github_delivery_id),

    CONSTRAINT ck_webhook_events_processing_status
        CHECK (
            processing_status IN (
                'RECEIVED',
                'PROCESSED',
                'FAILED'
            )
        )
);

CREATE INDEX idx_webhook_events_repository_id
    ON webhook_events (repository_id);

CREATE INDEX idx_webhook_events_event_type
    ON webhook_events (event_type);

CREATE INDEX idx_webhook_events_received_at
    ON webhook_events (received_at);

CREATE INDEX idx_webhook_events_processing_status
    ON webhook_events (processing_status);
