spring.application.name=projectsmaneger

spring.datasource.url=jdbc:postgresql://localhost:5432/projectsmaneger
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080

github.oauth.client-id=${GITHUB_CLIENT_ID}
github.oauth.client-secret=${GITHUB_CLIENT_SECRET}
github.oauth.redirect-uri=${GITHUB_OAUTH_REDIRECT_URI:http://localhost:8080/api/github/oauth/callback}
